blank_issues_enabled: false
contact_links:
  - name: "🚀 Quick Help - Development Guide"
    url: "https://github.com/enyukoo/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md"
    about: "Learn how to set up and run the application for development"
  
  - name: "💡 Ask a Question"
    url: "https://github.com/enyukoo/skills-expand-your-team-with-copilot/discussions"
    about: "Ask questions about how to use the system or get help with activities management"